apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nrfb068i5-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6f6a9ae0da67bc825cb50d970f8a2d0b593f3250@sha256:044ff90d627e9bffb37a9aca4fb0bbc30b11740bddac1f71979a859325896b7a
          name: container-image
